# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    # csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    php_errors:
        log: true

    #esi: true
    #fragments: true

    http_client:
        scoped_clients:
            coinGecko.client:
                base_uri: https://api.coingecko.com/api/v3/
                headers:
                    x-cg-demo-api-key: '%env(COINGECKO_API_KEY)%'
                    Accept: 'application/json'

            coinMarketCap.client:
                base_uri: https://pro-api.coinmarketcap.com/v1/
                headers:
                    X-CMC_PRO_API_KEY: '%env(COINMARKETCAP_API_KEY)%'
                    Accept: 'application/json'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_method_override: false

        # https://symfony.com/doc/5.4/deployment/proxies.html
        trusted_proxies: '127.0.0.1,REMOTE_ADDR'
        trusted_headers: ['x-forwarded-proto', 'x-forwarded-for']

        
